In [ ]:
import pandas as pd

In [30]:
LC_Issuance = pd.read_excel("Trade_Finance_Main.xlsm",skiprows=3,header=0,engine="openpyxl",usecols=['LC Number', 'Issue Date.', 'Project Director', 'Status', 'Bank', 'Facility Space', 'Beneficiary', 'Group Company', 'Project', 'Project Code', 'Curr', 'LC Amt(FCY)', 'Rate', 'LC Amt(SAR)', 'Expiry Date', 'Last Ship Date', 'Lines', 'Payment Terms', 'Cash Margin', 'Cash-Fund Utilized', 'Cash-Recovered', 'Increase Amount in SAR', 'Remarks', 'Active/Cancelled',]
).astype(
    {
        "Project Director":"category",
        "Status":"category",        
        "Bank":"category",
        "Facility Space":"category",
        "Beneficiary":"category",
        "Group Company":"category",
        "Project":"category",
        "Project Code":"Int32",
        "Curr":"category",
        "Lines":"category",
        
    }
)
LC_Issuance["Last Ship Date"] = pd.to_datetime(LC_Issuance["Last Ship Date"]).dt.date
LC_Issuance["Issue Date."] = pd.to_datetime(LC_Issuance["Issue Date."]).dt.date
LC_Issuance["Expiry Date"] = pd.to_datetime(LC_Issuance["Expiry Date"]).dt.date
LC_Issuance

c:\Users\FarhanAmanullaShaikh\PROJECTS\LC-Project\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\FarhanAmanullaShaikh\PROJECTS\LC-Project\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,LC Number,Issue Date.,Project Director,Status,Bank,Facility Space,Beneficiary,Group Company,Project,Project Code,...,Expiry Date,Last Ship Date,Lines,Payment Terms,Cash Margin,Cash-Fund Utilized,Cash-Recovered,Increase Amount in SAR,Remarks,Active/Cancelled
0,TF2331987203,2023-11-15,Hassan Taleb,Completed,Alinma,KSP,A. Abunayyan Trading Corporation,FIRST FIX,KSP,1020055,...,2024-05-31,2024-05-31,Credit,90 Days from Delivery Date,NaN,NaN,NaN,0.0,NaN,Cancelled
1,TF2319983726,2023-07-18,Hassan Taleb,Completed,Alinma,KSP,A. ABUNAYYAN TRADING CORPORATION,FIRST FIX,KSP,1020055,...,2023-10-16,2023-10-16,Credit,90 Days from Delivery Date,NaN,NaN,NaN,0.0,NaN,Cancelled
2,JLC6901470,2025-08-14,Muhammed Khan,Completed,Riyad,Cash,Abdul Aziz Mohammed Abu Shaiea Trading Est,IFAS,IFAS - Various Projects,<NA>,...,2025-09-30,2025-09-15,Cash,Sight,NaN,NaN,NaN,NaN,Margin refunded - 153759.93 SAR,Cancelled
3,JLC6801678,2024-09-10,Rabih Makhoul,Completed,Riyad,Cash,ABDULAH ABDIN ALBUKHARI FACTORY FOR,MBL,Neom - The Line,1020098,...,2025-02-28,2025-02-10,Cash,45 Days from Comm. Invoice Date,2679704.74,Abha,Yes,0.0,NaN,Cancelled
4,IM2431133001,2024-11-13,Rabih Makhoul,Completed,BAB,Multipurpose,Abdulah Abdin Albukhari Factory For Industry.,MBL,Neom - The Line,1020098,...,2025-01-31,2025-01-04,Credit,45 Days from Invoice Date,NaN,NaN,NaN,0.0,NaN,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,NaN,2026-06-22,Rabih Makhoul,Submitted to Bank,SNB,Opera House,Al Arabia Construction & Building Co.,MBL,Rabigh Power Plant,1020107,...,2026-10-31,2026-10-31,Credit,45 Days from the Invoice Date,NaN,NaN,NaN,0.0,to bank on 23-06,Active
952,NaN,2026-06-23,Nader Ageeb,Received to Open,NBK,Lagoon,Al Arabia for Construction & Building Co.,MBL,Lagoon,1020108,...,2026-11-21,2026-11-21,Credit,90 Days from Invoice Date,NaN,NaN,NaN,0.0,Anil Sir kept on hold for GA | NBK Prepared,Active
953,NaN,2026-06-23,Nader Ageeb,Received to Open,NBK,Lagoon,INDUSTRIAL STONES SOURCE,MBL,Lagoon,1020108,...,2026-11-21,2026-11-21,Credit,90 Days from Invoice Date,NaN,NaN,NaN,0.0,Anil Sir kept on hold for GA | NBK Prepared,Active
954,NaN,2026-06-23,Nader Ageeb,Received to Open,NBK,Lagoon,Modern Material Leaders,MBL,Lagoon,1020108,...,2026-11-21,2026-11-21,Credit,90 Days from Invoice Date,NaN,NaN,NaN,0.0,Anil Sir kept on hold for GA | NBK Prepared,Active
955,NaN,2026-06-23,Nader Ageeb,Received to Open,NBK,Lagoon,NIZAR ABDALGHANY KABLI FOR GENERAL CONTRACTING,MBL,Lagoon,1020108,...,2026-11-21,2026-11-21,Credit,90 Days from Invoice Date,NaN,NaN,NaN,0.0,Anil Sir kept on hold for GA | NBK Prepared,Active

In [28]:
LC_Issuance.columns

Index(['LC Number', 'Issue Date.', 'Project Director', 'Status', 'Bank',
       'Facility Space', 'Beneficiary', 'Group Company', 'Project',
       'Project Code', 'Curr', 'LC Amt(FCY)', 'Rate', 'LC Amt(SAR)',
       'Expiry Date', 'Last Ship Date', 'Lines', 'Payment Terms',
       'Cash Margin', 'Cash-Fund Utilized', 'Cash-Recovered',
       'Increase Amount in SAR', 'Remarks', 'Active/Cancelled'],
      dtype='str')

In [6]:
LC_Settlement = pd.read_excel("Trade_Finance_Main.xlsm",sheet_name="Main-Presentation",skiprows=3,header=0,engine="openpyxl")
LC_Settlement

c:\Users\FarhanAmanullaShaikh\PROJECTS\LC-Project\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\FarhanAmanullaShaikh\PROJECTS\LC-Project\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,LC Number,Date Recd,Presentation No,Project Director,Clean / Disc,Bank,Facility Space,Lines,Beneficiary,Group Company,...,Invoice Amt (SAR),Due Date,Payment Terms,Funds Utilize,Recovered,Remarks,Days,Tariff,Settlement Charges,Other Charges
0,TF2328386224,2024-01-14,1,Mohammed Kotb,Clean,Alinma,KSP,Cash,BRANCH OF TECON LIMITED,ICAD,...,246726.75,2024-01-08,0,Abha,Yes,NaN,0,NaN,1437.50,NaN
1,TF2328386224,2024-06-10,2,Mohammed Kotb,Clean,Alinma,KSP,Cash,BRANCH OF TECON LIMITED,ICAD,...,176755.45,2024-06-27,0,Abha,Yes,NaN,0,NaN,1437.50,NaN
2,TF2328386224,2024-07-24,3,Mohammed Kotb,Clean,Alinma,KSP,Cash,BRANCH OF TECON LIMITED,ICAD,...,275027.80,2024-07-25,0,Abha,Yes,NaN,0,NaN,1437.50,NaN
3,TF2328386224,2024-09-03,4,Mohammed Kotb,Discrepant,Alinma,KSP,Cash,BRANCH OF TECON LIMITED,ICAD,...,8510.00,2024-09-19,0,Abha,Yes,NaN,0,NaN,1437.50,NaN
4,TF2502300031,2025-02-20,1,Hassan Taleb,Clean,Alinma,KSP,Credit,ISAM KABBANI & PARTNERS LTD - UNITECH,FIRST FIX,...,500000.00,2025-05-12,90 Days from Invoice Date,JLC6800561-ADF Cash Margin Refund,No,NaN,90,NaN,1437.50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,JLC6901431_Cre,2026-05-13,11,Luis Puente,Clean,Riyad,Oceanarium,Credit,Mat Filtrasyon Teknolojeleri A.S,MBL,...,284755.58,2026-07-02,45 Days from Invoice Date,NaN,No,NaN,45,NaN,818.80,NaN
1609,TF2523000034,NaT,NaN,Rabih Makhoul,NaN,Alinma,KSP,Credit,Al Arabia Construction & Building Co.,MBL,...,48780.61,2026-06-25,45 Days from the Invoice Date,NaN,No,NaN,45,NaN,34827.75,NaN
1610,J212344,NaT,NaN,Matthew Mckernan,NaN,SNB,Opera House,Credit,Saudi Pro-Kitchen,MBL/ICAD,...,700000.00,2026-10-19,120 Days from Applicant representative sign on...,NaN,No,NaN,120,NaN,2505602.75,NaN
1611,ILC-0840-26-8758,NaT,NaN,AbdulAziz Eraiba Fawzi,NaN,Jazira,RCRC,Credit,Green Concrete CJSC,MBL,...,148788.15,2026-10-19,60 Days From Invoice Date,NaN,No,NaN,60,NaN,106930.45,NaN
1612,DCBWPM165531,NaT,NaN,Mohammed Kotb,NaN,SAB,MP1,Credit,DAIKIN AIR CONDITIONING SAUDI ARABIA LLC,MBL/ICAD,...,735855.00,2026-09-20,90 Days from Appln Rep Sign on Invoice,NaN,No,NaN,90,NaN,3172.85,NaN